version: "3"
services:
  mysql:
    container_name: postgresql_con
    image: postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx_con_2
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

    # build:
    #   dockerfile: Dockerfile
    #   context: ./frontend
    ports:
      - "80:80"
    # depends_on:
    #   - backend


