version: "3"
services:


  backend:
    container_name: spring-boot
    build: ../backend
    restart: always
    ports:
        - '8000:8000'
  mysql:
    container_name: postgresql_con
    image: postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    depends_on:
      - backend

  nginx:
    container_name: nginx_con_2
    image: nginx
    restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: ./frontend
    ports:
      - "80:80"


